FROM streamyard/gstreamer:$TARGET_ARCH-latest-dev-with-source

# Only development dependencies
FROM streamyard/gstreamer:$TARGET_ARCH-dev-dependencies

# And binaries built with debug symbols
COPY --from=0 /compiled-binaries /
